sudo: required
language: python

matrix:
  include:
   - os: linux
     dist: xenial
     python: "3.7"
     sudo: true
  fast_finish: true

install:
  - pip install -r requirements.travis.txt
  - pip install -e .
  - pip install --upgrade pip
  - pip install codecov &&
    pip install pytest &&
    pip install pytest-cov &&
    pip install coveralls &&
    conda install jupyter

script:
  - pytest --cov=timml tests/

after_success:
  - coveralls
